# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd21c0e0df17ca17446078df95c5a3b30b033c8f88843df37f44779eb985c936bed8f886840a6924e845f536568ea829cd095d1aeaac362da9c76f51486ed279

test:
  secret_key_base: 3b34f13bb1b21854f96a8f2fe4967df2dc779776e1e8d0436d0b5aa6919a7f3edca5fbd0e8af34f4ff537d6a1684900def4a8112bb794956829213ac09fb0dd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
